name: trailquest
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  flutter_svg: ^2.0.9
  flutter_animated_button: ^2.0.3
  web_socket_channel: ^2.1.0
  google_maps_flutter: ^2.6.1
  permission_handler: ^11.3.1

  cupertino_icons: ^1.0.6
  geolocator: ^11.0.0
  google_maps_routes: ^1.1.2
  http: ^0.13.6 
  flutter_polyline_points: ^1.0.0
  flutter_config: ^2.0.2
  firebase_core: any
  firebase_ui_auth: any
  google_sign_in: ^6.2.1
  firebase_ui_oauth_google: ^1.2.10
  firebase_auth: 4.12.0 #Remove = death. Needs to be 4.12 or else everything breaks see: https://stackoverflow.com/questions/77468892/error-authprovider-is-imported-from-both 
  geofence_service: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
 

flutter:
  uses-material-design: true
  assets:
    - assets/icons/img_home.svg
    - assets/icons/img_trails.svg
    - assets/icons/img_trophy.svg
    - assets/icons/img_profile.svg
    - assets/icons/arrow-sm-left-svgrepo-com (1).svg
    - assets/icons/img_filter.svg
    - assets/icons/img_arrow_right.svg
    - assets/icons/img_cross.svg
    - assets/icons/img_route.svg
    - assets/icons/img_trees.svg
    - assets/icons/img_city.svg
    - assets/icons/img_house_and_tree.svg
    - assets/icons/img_park.svg
    - assets/icons/img_round_arrow.svg
    - assets/icons/img_circular_arrow.svg
    - assets/icons/img_walking.svg
    - assets/icons/img_clock.svg
    - assets/icons/img_stairs.svg
    - assets/icons/img_arrow_up.svg
    - assets/icons/img_group.svg
    - assets/images/img_image_1.png
    - assets/images/Pelle_Svanslös-statyn.jpg
    - assets/images/gardsmyg_johan-nilsson.jpg
    - assets/images/FlyttblockSurte.jpg
    - assets/images/Luthagen.jpg
    - assets/images/wildflowers.jpg
    - assets/images/Uppsala_domkyrka_flygbild.jpg
    - assets/images/Logo.png
    
#  fonts:
#  - family: InterRegular
#    fonts: 
#      - asset: assets/fonts/InterRegular.ttf
#      - weight: 400
