import 'package:trailquest/widgets/trail_cards.dart';

/// An example list of trails - only used for testing purposes

List<TrailCard> MyTrailList = <TrailCard>[
  TrailCard(
    name: 'trail 1',
    stairs: false,
    lengthDistance: 5000,
    lengthTime: 60,
    natureStatus: 'City',
    heightDifference: 30,
    isSaved: true,
    isCircular: false,
    coordinates: [],
    image_path: 'assets/images/img_image_1.png',
  ),
  TrailCard(
    name: 'trail 2',
    stairs: false,
    lengthDistance: 5000,
    lengthTime: 60,
    natureStatus: 'City',
    heightDifference: 30,
    isSaved: true,
    isCircular: true,
    coordinates: [],
    image_path: 'assets/images/path_pic.jpg',
  ),
  TrailCard(
    name: 'trail 3',
    stairs: false,
    lengthDistance: 5000,
    lengthTime: 60,
    natureStatus: 'Nature',
    heightDifference: 30,
    isSaved: true,
    isCircular: true,
    coordinates: [],
    image_path: 'assets/images/img_image_1.png',
  ),
  TrailCard(
    name: 'trail 4',
    stairs: true,
    lengthDistance: 5000,
    lengthTime: 60,
    natureStatus: 'Nature',
    heightDifference: 30,
    isSaved: true,
    isCircular: false,
    coordinates: [],
    image_path: 'assets/images/img_image_1.png',
  ),
];

/// An example list of trails - only used for testing purposes

List<TrailCard> FriendTrailList = <TrailCard>[
  TrailCard(
    name: 'trail A',
    stairs: true,
    lengthDistance: 200,
    lengthTime: 3,
    natureStatus: 'City',
    heightDifference: 2,
    isSaved: false,
    isCircular: true,
    coordinates: [],
    image_path: 'assets/images/img_image_1.png',
  ),
  TrailCard(
    name: 'trail B',
    stairs: false,
    lengthDistance: 5000,
    lengthTime: 60,
    natureStatus: 'Nature',
    heightDifference: 30,
    isSaved: false,
    isCircular: false,
    coordinates: [],
    image_path: 'assets/images/img_image_1.png',
  ),
  TrailCard(
    name: 'trail C',
    stairs: false,
    lengthDistance: 5000,
    lengthTime: 60,
    natureStatus: 'Nature',
    heightDifference: 30,
    isSaved: false,
    isCircular: true,
    coordinates: [],
    image_path: 'assets/images/img_image_1.png',
  ),
  TrailCard(
    name: 'trail D',
    stairs: false,
    lengthDistance: 5000,
    lengthTime: 60,
    natureStatus: 'Nature',
    heightDifference: 30,
    isSaved: false,
    isCircular: false,
    coordinates: [],
    image_path: 'assets/images/img_image_1.png',
  ),
  TrailCard(
    name: 'trail E',
    stairs: false,
    lengthDistance: 5000,
    lengthTime: 60,
    natureStatus: 'Nature',
    heightDifference: 30,
    isSaved: false,
    isCircular: false,
    coordinates: [],
    image_path: 'assets/images/img_image_1.png',
  ),
];
