import 'package:trailquest/widgets/trail_cards.dart';

List<TrailCard> MyTrailList= <TrailCard>[
  TrailCard(
    name: 'trail 1',
    stairs: false, 
    lengthDistance: 5000,
    lengthTime: 60,
    natureStatus: 'Nature',
    heightDifference: 30,
    isSaved: true,
  ),
  TrailCard(
    name: 'trail 2',
    stairs: false, 
    lengthDistance: 5000,
    lengthTime: 60,
    natureStatus: 'Nature',
    heightDifference: 30,
    isSaved: true,
  ),
  TrailCard(
    name: 'trail 3',
    stairs: false, 
    lengthDistance: 5000,
    lengthTime: 60,
    natureStatus: 'Nature',
    heightDifference: 30,
    isSaved: true,
  ),
  TrailCard(
    name: 'trail 4',
    stairs: false, 
    lengthDistance: 5000,
    lengthTime: 60,
    natureStatus: 'Nature',
    heightDifference: 30,
    isSaved: true,
  ),
];

List<TrailCard> FriendTrailList= <TrailCard>[
  TrailCard(
    name: 'trail A',
    stairs: true, 
    lengthDistance: 200,
    lengthTime: 3,
    natureStatus: 'City',
    heightDifference: 2,
    isSaved: false,
  ),
  TrailCard(
    name: 'trail B',
    stairs: false, 
    lengthDistance: 5000,
    lengthTime: 60,
    natureStatus: 'Nature',
    heightDifference: 30,
    isSaved: false,
  ),
  TrailCard(
    name: 'trail C',
    stairs: false, 
    lengthDistance: 5000,
    lengthTime: 60,
    natureStatus: 'Nature',
    heightDifference: 30,
    isSaved: false,
  ),
  TrailCard(
    name: 'trail D',
    stairs: false, 
    lengthDistance: 5000,
    lengthTime: 60,
    natureStatus: 'Nature',
    heightDifference: 30,
    isSaved: false,
  ),
  TrailCard(
    name: 'trail E',
    stairs: false, 
    lengthDistance: 5000,
    lengthTime: 60,
    natureStatus: 'Nature',
    heightDifference: 30,
    isSaved: false,
  ),
];